# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Corr"
license = "MIT"
licenselink = ""
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = "0.21"

[author]
  name = "Benjamin Richardson"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
